runtime: python
env: flex

runtime_config:
    python_version: 3

env_variables:
    MEMCACHEDCLOUD_SERVERS: ""
    MEMCACHEDCLOUD_USERNAME: ""
    MEMCACHEDCLOUD_PASSWORD: ""

entrypoint: gunicorn -w 4 -b :$PORT -k gevent fullrss:app
